#ifndef __INCLUDES_HPP__
#define __INCLUDES_HPP__

#include "enums.hpp"
#include "type_variable.hpp"
#include "par.hpp"
#include "expr.hpp"
#include "def.hpp"
#include "function_type.hpp"
#include "array_index.hpp"
#include "array_type.hpp"
#include "ast.hpp"
#include "bin_op.hpp"
#include "bool.hpp"
#include "float.hpp"
#include "char.hpp"
#include "delete.hpp"
#include "dim.hpp"
#include "for_down_to.hpp"
#include "for.hpp"
#include "for_to.hpp"
#include "function_call.hpp"
#include "if.hpp"
#include "int.hpp"
#include "let_def.hpp"
#include "letin.hpp"
#include "lexer.hpp"
#include "new.hpp"
#include "parser.hpp"
#include "ref_type.hpp"
#include "string.hpp"
#include "unit.hpp"
#include "un_op.hpp"
#include "while.hpp"
#include "var_def.hpp"
#include "array_def.hpp"
#include "function_def.hpp"
#include "const_def.hpp"
#include "id.hpp"

constexpr bool debug = false;

#endif